apiVersion: apps/v1
kind: Deployment
metadata:
  name: theta
spec:
  replicas: 1
  selector:
    matchLabels:
      app: theta
  template:
    metadata:
      labels:
        app: theta
    spec:
      containers:
        - image: ghcr.io/thedevtop/theta-go:latest
          imagePullPolicy: Always
          name: theta
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: theta
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 1958
      protocol: TCP
      targetPort: 1958
  selector:
    app: theta
